static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6000
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 1s
            enable_redirection: true
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster 
          downstream_auth_password:
            inline_string: "123456"
  clusters:
  - name: redis_cluster
    connect_timeout: 1s
    cluster_type:
      name: envoy.clusters.redis
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 7001
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.2
                port_value: 7002
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.3
                port_value: 7003
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.4
                port_value: 7004
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.5
                port_value: 7005
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.6
                port_value: 7006
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          auth_password:
            inline_string: "123456"
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
